name: Create new release

on:
  push:
    tags:
      - '20[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'

jobs:
  build:
    name: Create release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - uses: actions/setup-node@v3
        with:
          node-version: 19
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: npm install

      - name: Get package version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Create artifact
        run: zip -r ${{ steps.get_version.outputs.VERSION }}.zip . -x '.github**' -x '.git**' -x '.gitignore' -x '.gitattributes'

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ${{ steps.get_version.outputs.VERSION }}.zip
          tag_name: ${{ github.ref }}
          name: ${{ github.ref }}
          draft: false
          prerelease: false
